### ISSUE TITLE
[User feedback] Bulk Select Not Working

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#173] opened 2020-07-30 13:16 UTC
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/projects/new

Bulk Select Not Working

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1596114963737699453.png )

**Comment by adrianq** [comment] 2020-07-31 10:53
Cannot reproduce this error in any step. Can you let me know the step number? I cannot see it in the screenshot (we need to review the feedback tool because it is cropping the screenshots)

**Comment by adrianq** [comment] 2020-08-06 10:34
I think we agree this is not an error so I am closing the issue. Feel free to reopen it if this not the case...

**Closed by adrianq** 2020-08-06 10:34 UTC
